spring:
  cloud:
    stream:
      bindings:
        output:
          destination: top
        input:
          destination: top
          group: group001



      rocketmq:
        binder:
          name-server: 14.18.72.130:9876
        bindings:
          input:
            consumer:
              tags: tag01





server:
  port: 9001

logging:
  level:
   - org.springframework.cloud.stream.*: debug